name: Linux Test Build

on:
    workflow_dispatch: {}
    push:
        tags: ["run*"]
        # tags: ["v*.*.*"]
        # branches: [ "*" ]
        # paths:
        #   - "UE4SS/src/**"
        #   - "UE4SS/include/**"
        #   - "UE4SS/generated_src/**"
        #   - "UE4SS/generated_include/**"
        #   - "deps/**"
        #   - "UE4SS/proxy_generator/**"
        #   - ".github/workflows/linux-test.yml"
        #   - "CMakeLists.txt"
        #   - "cmake/**"
        #   - tools/**
        #   - xmake.lua

jobs:
    make-release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: korandoru/setup-zig@v1
              with:
                  zig-version: 0.13.0 # released versions or master
            - run: zig version

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  # components: rustfmt, clippy
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y nim build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc-dev-arm64-cross ccache

            - name: Setup xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: "2.3.3"
                  build-cache: true
                  build-cache-key: "xmake-build-cache"
                  build-cache-path: "build/.build_cache"
                  actions-cache-folder: "build/.xmake-cache"
                  actions-cache-key: "xmake-actions-cache"
            - name: Build
              run: |
                  xmake f -y --ue4ssUI=TUI --ue4ssInput=y --ue4ssIsBeta=y --zig=y -m "Game__Shipping__Linux" -a arm64 -vD --clean
                  XMAKE_COLORTERM=nocolor xmake build -v -D > build.log
            - name: Stripping
              run: |
                  mkdir prepackage
                  objcopy --only-keep-debug Binaries/Game__Shipping__Linux/UE4SS/libUE4SS.so ./prepackage/libUE4SS.so.debug
                  cp Binaries/Game__Shipping__Linux/UE4SS/libUE4SS.so ./prepackage/libUE4SS.so
                  strip --strip-debug --strip-unneeded ./prepackage/libUE4SS.so
                  cd ./prepackage && objcopy --add-gnu-debuglink=libUE4SS.so.debug ./libUE4SS.so && cd ..
            - name: Package
              run: python ./tools/buildscripts/build.py package -d ./prepackage -s linux64
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Linux-Release
                  path: |
                      release/zDEV-UE4SS_0.0.0.zip
                      build.log
