name: Linux Test Build

on:
    workflow_dispatch: {}
    push:
        tags: ["run*"]
        # tags: ["v*.*.*"]
        # branches: [ "*" ]
        # paths:
        #   - "UE4SS/src/**"
        #   - "UE4SS/include/**"
        #   - "UE4SS/generated_src/**"
        #   - "UE4SS/generated_include/**"
        #   - "deps/**"
        #   - "UE4SS/proxy_generator/**"
        #   - ".github/workflows/linux-test.yml"
        #   - "CMakeLists.txt"
        #   - "cmake/**"
        #   - tools/**
        #   - xmake.lua

jobs:
    make-release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            # This is used to complete the identity challenge
            # with sigstore/fulcio when running outside of PRs.
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y nim build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc-dev-arm64-cross ccache cmake clang libclang-dev

            # - name: Install LLVM 19
            #   uses: KyleMayes/install-llvm-action@v2
            #   with:
            #       version: "19.0"
            - name: Setup LLVM
              uses: ZhongRuoyu/setup-llvm@v0
              with:
                  llvm-version: 19
            - name: Build Zig compiler
              run: |
                  git clone https://github.com/ziglang/zig.git
                  cd zig && mkdir build && cd build
                  cmake .. -DCMAKE_BUILD_TYPE=Release
                  make -j$(nproc)
                  sudo make install

            - name: Verify Build
              run: |
                  ./zig/build/zig version
                  sudo ln -s ./zig/build/zig /usr/local/bin/zig
            # - uses: korandoru/setup-zig@v1
            #   with:
            #       zig-version: master
            # - uses: mlugg/setup-zig@v1
            #   with:
            #       version: 0.13.0
            # - run: |
            #       which zig
            #       sudo ln -s $(which zig) /usr/local/bin/zig

            - name: Change chmod for zig
              run: |
                  sudo chmod +x /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-c++
                  sudo /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-c++ --version
                  sudo chmod +x /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-cc
                  sudo /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-cc --version
                  sudo chmod +x /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-ar
                  sudo /home/runner/work/RE-UE4SS/RE-UE4SS/tools/zig/zig-ar --version

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  # components: rustfmt, clippy

            - name: Setup xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                  xmake-version: "latest"
                  build-cache: true
                  build-cache-key: "xmake-build-cache"
                  build-cache-path: "build/.build_cache"
                  actions-cache-folder: "build/.xmake-cache"
                  actions-cache-key: "xmake-actions-cache"
            - name: Build
              run: |
                  xmake f -y --ue4ssUI=TUI --ue4ssInput=y --ue4ssIsBeta=y --zig=y -m "Game__Shipping__Linux" -vD --clean --toolchain=zigcross
                  echo "Clean build done.. next building..."
                  xmake build -v -D
            - name: Stripping
              run: |
                  mkdir prepackage
                  objcopy --only-keep-debug Binaries/Game__Shipping__Linux/UE4SS/libUE4SS.so ./prepackage/libUE4SS.so.debug
                  cp Binaries/Game__Shipping__Linux/UE4SS/libUE4SS.so ./prepackage/libUE4SS.so
                  strip --strip-debug --strip-unneeded ./prepackage/libUE4SS.so
                  cd ./prepackage && objcopy --add-gnu-debuglink=libUE4SS.so.debug ./libUE4SS.so && cd ..
            - name: Package
              run: python ./tools/buildscripts/build.py package -d ./prepackage -s linux64
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Linux-Release
                  path: |
                      release/zDEV-UE4SS_0.0.0.zip
                      build.log
